---
- name: create 2 text files
  hosts: localhost
  
  - name: create two txt files
    file:
      path: '{{ item.name }}'
      state: touch

    loop:
      - {name: '~/Documents/file1.txt'}
      - {name: '~/Documents/file2.txt'}